name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        poetry-version: [ "1.8.4" ]
        os: [ ubuntu-22.04 ]
        # poetry-version: ["latest", "main", "1.8.4"]
        # os: [ ubuntu-22.04, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs:
      - codestyle
      - lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install poetry
        run: poetry install

      - name: Run test
        run: poetry run pytest --cov --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "latest"

      - name: Install poetry
        run: poetry install

      - name: Run codestyle
        run: poetry run pycodestyle red_forest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "latest"

      - name: Install poetry
        run: poetry install

      - name: Run lint
        run: poetry run pylint red_forest
        continue-on-error: true
